# Generated by Django 3.1.7 on 2021-03-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_courses_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='title',
            new_name='name',
        ),
    ]
