# Generated by Django 3.1.7 on 2021-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_courses_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
